// Code generated by devtools/gen. DO NOT EDIT.

// Package en_us_utf8 orders strings exactly as strcoll does for the
// en_US.UTF-8 locale of glibc 2.41.
//
// The tables are the compiled LC_COLLATE data of en_US.utf8 in the
// locale-archive of postgres:18@sha256:74935e72241653ca55e0414067e6d8763aceb8a810eb51b452253ec3dcfc4336
// (linux/amd64), which ships Debian glibc 2.41-12+deb13u4.
// The sha256 of that LC_COLLATE file is f062bf818ec7c394208e4b12db855fbe3765ca1463b2e0cfe05e434f1c293981.
//
// Importing this package registers [Collation] with collate.Register,
// so that collate.Lookup("en_US.UTF-8", "2.41") returns it.
package en_us_utf8

import (
	"github.com/k1LoW/glibctext/collate"
	"github.com/k1LoW/glibctext/internal/tables/lccollate_f062bf818ec7"
)

// Collation orders strings as strcoll_l does for en_US.UTF-8 with glibc 2.41
// (Debian 2.41-12+deb13u4).
var Collation collate.Collation = lccollate_f062bf818ec7.Table

func init() {
	collate.Register("en_US.UTF-8", "2.41", Collation)
}
