// Code generated by devtools/gen. DO NOT EDIT.

// Package en_us_utf8 maps the case of characters exactly as towlower and
// towupper do for the en_US.UTF-8 locale of glibc 2.41.
//
// The tables are the compiled LC_CTYPE data of en_US.utf8 in the
// locale-archive of postgres:18@sha256:74935e72241653ca55e0414067e6d8763aceb8a810eb51b452253ec3dcfc4336
// (linux/amd64), which ships Debian glibc 2.41-12+deb13u4.
// The sha256 of that LC_CTYPE file is 1257597210f43630e7c8a745ae95127e96b93a43515ac5163cab459ddc1664b3.
//
// Importing this package registers [Ctype] with ctype.Register,
// so that ctype.Lookup("en_US.UTF-8", "2.41") returns it.
package en_us_utf8

import (
	"github.com/k1LoW/glibctext/ctype"
	"github.com/k1LoW/glibctext/internal/tables/lcctype_1257597210f4"
)

// Ctype maps case as towlower_l and towupper_l do for en_US.UTF-8 with glibc 2.41
// (Debian 2.41-12+deb13u4).
var Ctype ctype.Ctype = lcctype_1257597210f4.Table

func init() {
	ctype.Register("en_US.UTF-8", "2.41", Ctype)
}
